######################################################################
# Automatically generated by qmake (2.01a) Sat May 16 13:09:29 2009
######################################################################

TEMPLATE = app

QT += script
QT += widgets

# Input
SOURCES += hp15c.cpp
RESOURCES += hp15c.qrc
ICON = hp15c.icns
RC_FILE = hp15c.rc
